language: node_js
node_js:
  - stable
addons:
  chrome: stable
branches:
  only:
    - master
    - "/^greenkeeper.*$/"
before_install:
  - google-chrome-stable --headless --disable-gpu
install:
  - npm install
script:
  - npm test
  - npm run build
after_success:
  - codecov
